# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 Open Education Polito.
#
# fare is free software; you can redistribute it and/or modify it under the
# terms of the MIT License; see LICENSE file for more details.

addons:
    # chrome: stable

dist: bionic # Chrome driver fails if not trusty dist

notifications:
  email: # sent to the committer and the author
    on_success: never # default: always
    on_failure: always # default: always

language: python

jobs:
  fast_finish: true

cache:
  - pip

services:
  - docker

env:
  global:
    # Print screenshots to console output
    - E2E_OUTPUT=base64
    # Enable end-to-end tests
    - E2E=no
  jobs:
    # Momentarily disable E2E tests
    # Momentarily disable prod testing to speed up dev
    #- REQUIREMENTS=prod #E2E=yes
    - REQUIREMENTS=qa

python:
  - "3.6.4"

before_install:
  # Stop default travis services
  - "sudo service mysql stop"
  - "sudo service postgresql stop"
  # Make dir for logs
  - "sudo mkdir /var/log/fare && sudo chmod 777 /var/log/fare -R"
  # Start docker services
  - "docker-compose up -d"
  # Momentarily disable E2E tests
  # Chrome webdriver for Selenium
  #- "PATH=$PATH:$HOME/webdrivers"
  #- "if [ ${E2E} == 'yes' ] && [ ! -f $HOME/webdrivers/chromedriver ]; then wget https://chromedriver.storage.googleapis.com/2.7/chromedriver_linux64.zip -P $HOME/webdrivers; unzip -d $HOME/webdrivers $HOME/webdrivers/chromedriver_linux64.zip; fi"
  - "nvm install 6; nvm use 6"
  - "travis_retry pip install --upgrade pip setuptools py pipenv"
  - "travis_retry pip install twine wheel coveralls"

install:
  - "./scripts/bootstrap"

before_script:
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/
  #- "export DISPLAY=:99.0"
  #- "if [ ${E2E} == 'yes' ]; then sh -e /etc/init.d/xvfb start; sleep 3; fi"
  # Allow services running inside docker to start
  - "./docker/wait-for-services.sh"

script:
  - ./scripts/server &
  - ./run-tests.sh # E2E tests are skipped if E2E env is set to 'no'

after_success:
  - coveralls
